#!/bin/bash
set -e
 
# Create cache dir if needed
if [ ! -d $OPENSHIFT_REPO_DIR/app/cache ]; then
    mkdir $OPENSHIFT_REPO_DIR/app/cache
fi
chmod -Rv 777 $OPENSHIFT_REPO_DIR/app/cache
 
# Create logs dir if needed
if [ ! -d $OPENSHIFT_REPO_DIR/app/logs ]; then
    mkdir $OPENSHIFT_REPO_DIR/app/logs
fi
chmod -Rv 777 $OPENSHIFT_REPO_DIR/app/logs
